import { BuildingType } from '../game/BuildingType';
import type { BuildingModelName } from './AssetLoader';

/**
 * Maps each BuildingType to its GLTF model filename.
 * Shared between BuildingRenderer and PlacementController.
 */
export const BUILDING_MODEL_MAP: Record<BuildingType, BuildingModelName> = {
  [BuildingType.Castle]: 'castle',
  [BuildingType.WoodcutterHut]: 'woodcutter_hut',
  [BuildingType.ForesterHut]: 'foresters_hut',
  [BuildingType.Quarry]: 'quarry',
  [BuildingType.FishermanHut]: 'fisherman_hut',
  [BuildingType.GuardHut]: 'guard_hut',
  [BuildingType.Sawmill]: 'sawmill',
  [BuildingType.Farm]: 'farm',
  [BuildingType.GeologistHut]: 'geologist_hut',
  [BuildingType.IronMine]: 'iron_mine',
  [BuildingType.CoalMine]: 'coal_mine',
  [BuildingType.GoldMine]: 'gold_mine',
  [BuildingType.StoneMine]: 'stone_mine',
  [BuildingType.Watchtower]: 'watchtower',
  [BuildingType.Windmill]: 'windmill',
  [BuildingType.Bakery]: 'bakery',
  [BuildingType.PigFarm]: 'pig_farm',
  [BuildingType.Slaughterhouse]: 'slaughterhouse',
  [BuildingType.IronSmelter]: 'iron_smelter',
  [BuildingType.ToolmakerWorkshop]: 'toolmaker_workshop',
  [BuildingType.GoldsmithMint]: 'goldsmith_mint',
  [BuildingType.BlacksmithArmory]: 'blacksmith_armory',
  [BuildingType.Barracks]: 'barracks',
  [BuildingType.Warehouse]: 'warehouse',
  [BuildingType.Harbor]: 'harbor',
  [BuildingType.SmallHouse]: 'small_house',
  [BuildingType.MediumHouse]: 'medium_house',
  [BuildingType.LargeHouse]: 'large_house',
  // Expansion buildings
  [BuildingType.Well]: 'well',
  [BuildingType.Orchard]: 'orchard',
  [BuildingType.Vineyard]: 'vineyard',
  [BuildingType.Winery]: 'winery',
  [BuildingType.Brewery]: 'brewery',
  [BuildingType.DairyFarm]: 'dairy_farm',
  [BuildingType.CheeseMakerBuilding]: 'cheese_maker_building',
  [BuildingType.Hayfield]: 'hayfield',
  [BuildingType.Tannery]: 'tannery',
  [BuildingType.WeaversHut]: 'weavers_hut',
  [BuildingType.CharcoalBurner]: 'charcoal_burner',
  [BuildingType.FletchersWorkshop]: 'fletchers_workshop',
  [BuildingType.SiegeWorkshop]: 'siege_workshop',
  [BuildingType.Stable]: 'stable',
  [BuildingType.CattleRanch]: 'cattle_ranch',
  [BuildingType.SheepFarm]: 'sheep_farm',
  [BuildingType.Butchery]: 'butchery',
  [BuildingType.Fortress]: 'fortress',
  [BuildingType.ArcheryRange]: 'archery_range',
  [BuildingType.TorchTower]: 'torch_tower',
  [BuildingType.InnTavern]: 'inn_tavern',
  [BuildingType.Market]: 'market',
  // Living World buildings (placeholder models until real ones are created)
  [BuildingType.HuntingLodge]: 'hunting_lodge',
  [BuildingType.TrappersHut]: 'trappers_hut',
  [BuildingType.Furrier]: 'furrier',
  [BuildingType.Apiary]: 'apiary',
  [BuildingType.Meadery]: 'meadery',
};
